### ISSUE TITLE
Small values (non-integer) look choppy, not smooth

### ISSUE THREAD

**Issue by userqt** [tweenjs/tween.js#628] opened 2022-06-24 10:17 UTC
I am tweening a simple animation on the x axis from values between -10 to -8. This is done over the course of 20 frames. It looks choppy. Are non-integer points (floating point values) not interpolated? It should tween I suppose in this way: -10->-9.5->-9->-8.5....
But it doesnt look to be doing that. It simply "jumps" to the integer value -10->-9->-8. 

How can this be resolved?

**Comment by Carlos920** [comment] 2022-06-27 02:15
You can try this [using a custom easing function](http://tweenjs.github.io/tween.js/docs/user_guide.html#using-a-custom-easing-function)

**Comment by trusktr** [comment] 2022-06-27 02:46
@userqt Hello! This is a duplicate of https://github.com/tweenjs/tween.js/issues/116

**Closed by trusktr** 2022-06-27 02:46 UTC
