### ISSUE TITLE
Stopping chained tweens is broken

### ISSUE THREAD

**Issue by JasXSL** [tweenjs/tween.js#406] opened 2018-01-23 15:54 UTC
Your example is broken too. Try stopping it while the green circle animates. The stop command is ignored.
http://tweenjs.github.io/tween.js/examples/11_stop_all_chained_tweens.html

**Comment by JasXSL** [comment] 2018-01-23 16:55
As a workaround, I've stored each value in an array and am stopping each one separately. However, if you try to stop them within the onComplete event, the program crashes (nodejs):

<pre>
TypeError: Cannot set property '_isPlaying' of undefined
    at _Group.update (/home/pi/vibhub/node_modules/@tweenjs/tween.js/src/Tween.js:65:43)
    at Client.tick (/home/pi/vibhub/Client.js:123:9)
    at Timeout.Client.interval.setInterval [as _onTimeout] (/home/pi/vibhub/Client.js:80:7)
    at ontimeout (timers.js:478:11)
    at tryOnTimeout (timers.js:302:5)
    at Timer.listOnTimeout (timers.js:262:5)
</pre>

A workaround for the workaround involves setting a timer:

<pre>
setTimeout(() => {
  clearTweens();
}, 1);
</pre>

This works, but it's not very elegant.

**Comment by teamplanimal** [comment] 2018-02-10 01:14
FYI, I had this issue as well, my workaround was to move `this.stopChainedTweens();` to the top of the stop() function as opposed to the end.

**Comment by trusktr** [comment] 2018-03-15 18:03
Thanks for reporting. Will have a 👀

**Comment by trusktr** [comment] 2018-03-15 18:33
Doesn't look like the PR that introduced the feature covers this case: https://github.com/tweenjs/tween.js/commit/d8b2deb02c2d6fad9b7fdb5a9511669ef86d07dd

Must've been a TODO!

**Comment by zhnoah** [comment] 2019-06-27 02:33
Is there any zero hour solution before the problem is solved? Loop execution stop command?

**Comment by mikebolt** [comment] 2019-06-27 04:47
Don't use the chain function. Chain tweens by calling .start in an
onComplete callback.

**Comment by trusktr** [comment] 2020-05-30 03:25
I reverted the tests that were removed for `stopChainedTweens` in https://github.com/tweenjs/tween.js/pull/525, and merged in your changes @NorthernCaptain, and it works! Thanks! :tada:

**Closed** 2020-05-30 03:28 UTC
