### ISSUE TITLE
onComplete() being called twice

### ISSUE THREAD

**Issue by WyattHRichter** [tweenjs/tween.js#308] opened 2016-12-27 03:15 UTC
tween.js version: 16.3.5
browser: Chrome Version 55.0.2883.87 (64-bit) Linux (Ubuntu)

hey! great lib, thanks for maintaining it!

here's a replication of one of my tweens:

```
new TWEEN.Tween({t:0}).to({t:1},1000).onUpdate(function(){
    //perform action
}).onComplete(function(){
    //called twice occasionally
    callback();
}).start();
```

The function called by onComplete is called twice occasionally. Debugging it, I found that the first onComplete would be called, then after many calls of `TWEEN.update()`, the second onComplete would be called.

Here is the stack trace to the second onComplete call:
```
(anonymous) (guiBox.js:88)     //my code in onComplete
update (Tween.js:387)          //_onCompleteCallback.call(_object);
update (Tween.js:56)           //if (_tweens[i].update(time) || preserve) {
startScreenLoop (intro.js:227) //my loop that calls TWEEN.update()
```

thank you!

**Comment by mikebolt** [comment] 2016-12-29 19:59
I could not reproduce this issue with Chrome 55.0.2883.95 on Mac. Could you provide some code that demonstrates the issue? I can test it on Debian or Ubuntu later, if necessary.

**Comment by dalisoft** [comment] 2017-03-19 17:16
My [es6-version tween.js](https://github.com/tweenjs/es6-tween/releases/tag/v0.1.10) offers `once` event that fired once, can fix this issue. Try out, not too hard to get started, easy as original tween.js

**Comment by madivivek** [comment] 2017-05-12 10:57
i too am facing the same issue. 
tweenBack = new TWEEN.Tween(font)
.to({value: 45},200)
.onUpdate(this.updateFont.bind(this))
.onComplete(reels.checkautospin);

the functoin reels.checkautospin is called twice

**Comment by dalisoft** [comment] 2017-05-12 12:42
I not sure why, but this issue does not appear for me. Can you provide the example on Codepen or jsfiddle for better answer as well as community solution. Always the best fixes comes from more peoples rather than one or two peoples. Fix me if something wrong on my message. Thanks

**Comment by trusktr** [comment] 2017-09-16 20:52
We need a working example that shows the problem so we can run it. That's the best way to solve this.

**Comment by mikebolt** [comment] 2019-06-06 04:25
Tween.js no longer uses an array to store tweens and the Tween.update code is smarter now. Because this issue is covered by [a test](https://github.com/tweenjs/tween.js/blob/master/test/unit/tests.js#L724) I'm closing this.

**Closed by mikebolt** 2019-06-06 04:25 UTC
Labels: Bug
