### ISSUE TITLE
Tween.js v19 + Three.js r151 = chain() don't work correctly 

### ISSUE THREAD

**Issue by Turtleted21** [tweenjs/tween.js#643] opened 2023-04-19 11:35 UTC
Hello

Since Three.js r151 Tween is no longer delivred with Three. So I try to import Tween v19 to Three r151 but chain() don't work correctly now.

I made this glitch demo : https://glitch.com/edit/#!/luminous-spectrum-prince
it use Three.js r151 and the "_tween.module.min.js_" delivred with Three.js r145 -> chain() work perfectly.

Now in the js file if you comment the line :  _import { TWEEN }  from "./tween.module.min.js";_ to use  :     _<script src="https://cdnjs.cloudflare.com/ajax/libs/tween.js/19.0.0/tween.umd.js"></script>_ in the html file
chain() don't work correctly , after the second chain() the cube position restart from y:0 (initial cube position) instead restart from y:-300
glitch demo with bug : https://glitch.com/edit/#!/sky-right-tarn

Thanks to help me

**Comment by trusktr** [comment] 2023-04-21 19:37
Hello! This is the newer expected behavior because it allows the exact same animation to be repeated.

Here's one way to solve that, using an initial tween:

https://glitch.com/edit/#!/alpine-glen-warrior

We are tracking a feature to make this easy.

Duplicate of #522

**Closed by trusktr** 2023-04-21 19:37 UTC

**Comment by trusktr** [comment] 2023-04-21 20:27
Here is another way to solve it without the extra Tween:

https://glitch.com/edit/#!/gainful-speckle-gopher

This one chains them with onComplete and calling start(time, **true**) where the `true` tells it to start a Tween using whatever the last values were.
