### ISSUE TITLE
Using tween.start() a second time doesn't reset starting values

### ISSUE THREAD

**Issue by chepe263** [tweenjs/tween.js#512] opened 2020-01-14 21:47 UTC
I have a situation using yoyo and repeat in a tween.
I'm using tween.js to animate the opacity of a circle. The idea is to smoothly set opacity to 1 and back to 0. I'm using `yoyo` to for it but It has an unexpected behavior when I use `start` a second time.

The first time, the tween goes from 0 smoothly to 1, then smoothly back to 0.
The second time, the tween goes from 0 to abruptly to 1, then smoothly back to 0.

https://codepen.io/ppp000/pen/RwNBVYR

The expected behavior is the first time, the tween goes from 0 smoothly to 1, then smoothly back to 0.
The second time (and any other times), the tween goes from 0 smoothly to 1, then smoothly back to 0.

https://codepen.io/ppp000/pen/VwYBWLm?editors=1011

To make it work, I have to set again the `to({})` method, and `tween._valuesStart.opacity`. `_valuesStart` is not a public property so setting it doesn't seem valid.

**Comment by trusktr** [comment] 2020-01-15 02:03
Yoyo has some issues:

- This issue
- https://github.com/tweenjs/tween.js/issues/284
- https://github.com/tweenjs/tween.js/issues/178
- https://github.com/tweenjs/tween.js/issues/173


It'd be great to circle back around to making Yoyo work cleanly.

In the meantime, you could try a workaround like using `.chain()` to chain two animations, one going from 0 to 1, and the other going from 1 to 0.

**Comment by trusktr** [comment] 2020-01-15 02:28
Another workaround, also using only public API, is to trigger a second tween in `onComplete`.

**Comment by chepe263** [comment] 2020-01-15 02:32
I was trying to reuse tweens and triggering `start` with `onComplete` had a
weird result when trying to start the same tween a second time.

**Comment by mikebolt** [comment] 2020-01-15 19:29
The api wasn’t designed for this. I suggest creating a new tween.

I may be able to fix how multiple calls to start() work. Also, I am going
to make complete API documentation, so whether I change it or not, the
intended behavior will be less ambiguous.

**Comment by chepe263** [comment] 2020-01-15 20:14
I was wondering if storing the `_valuesStart` and `_valuesEnd` and setting them again when `start` is called would be enough and the right solution. What do you think?

**Comment by trusktr** [comment] 2020-05-29 18:28
> had a weird result when trying to start the same tween a second time.

Yep, that's currently an issue. It is best to start a second _new_ tween than the same tween, because tweens always want to start at the initial values rather than at the last value where it ended. Also if you manually call `tween.update`, then there's an issue where `onComplete` will not set the `isPlaying` to false.

To get around the issue of `isPlaying` not becoming false on `onComplete`, you can 

- use a `Group` (see docs)
- or use the global `TWEEN` object (which is a `Group`)
- or add this to your tween: `tween.onComplete(() => tween.stop())` (in this case you don't need to use `Group` or `TWEEN`)

To have the tween start at the last known values, then when a tween is completed or stopped, you should create a new tween with the new initial value to start at.

I'd like to improve this situation.

Was there any other issue you found?

> I was wondering if storing the _valuesStart and _valuesEnd and setting them again when start is called would be enough and the right solution. What do you think?

I have an idea for API improvement, with backwards compatibility:

```
new TWEEN.Tween(objectWithInitialValues, {rememberLastValues: true})
```

where `rememberLastValues` would make it so any time you call `start()` it will start with the last value where it previously was.

This will greatly improve the experience (f.e. it will make end user code much cleaner because instead of having multiple Tween instances we can have just one).

Here is a before and after code example to achieve the same thing:

<details><summary>before, 51 lines of code (you have to do something like this currently):</summary>

```js
class ExampleBeforeAPIChanges {
	openTween = null
	closeTween = null
	menuOpen = false
	tweenRAF = null

	makeOpenTween() {
		this.openTween = new TWEEN.Tween({menuPosition: (someObject && someObject.position.x) || 0})
			.onComplete(() => this.openTween.stop())
			.onUpdate(obj => (someObject.position.x = obj.menuPosition))
			.easing(TWEEN.Easing.Exponential.Out)
	}

	makeCloseTween() {
		this.closeTween = new TWEEN.Tween({menuPosition: (someObject && someObject.position.x) || -MENU_WIDTH})
			.onComplete(() => this.closeTween.stop())
			.onUpdate(obj => (someObject.position.x = obj.menuPosition))
			.easing(TWEEN.Easing.Exponential.Out)
	}

	openMenu = () => {
		this.menuOpen = true

		if (this.closeTween && this.closeTween.isPlaying()) this.closeTween.stop()

		this.makeOpenTween()
		this.openTween.to({menuPosition: -MENU_WIDTH}, 800).start()
		this.tweenLoop()
	}

	closeMenu = () => {
		this.menuOpen = false

		if (this.openTween && this.openTween.isPlaying()) this.openTween.stop()

		this.makeCloseTween()
		this.closeTween.to({menuPosition: 0}, 800).start()
		this.tweenLoop()
	}

	toggleMenu = () => (this.menuOpen ? this.closeMenu() : this.openMenu())

	tweenLoop() {
		if (this.tweenRAF) return

		this.tweenRAF = requestAnimationFrame(function loop(t) {
			if (this.openTween && this.openTween.isPlaying()) this.openTween.update(t)
			else if (this.closeTween && this.closeTween.isPlaying()) this.closeTween.update(t)
            else return (this.tweenRAF = null)
            this.tweenRAF = requestAnimationFrame(loop)
		})
    }
}
```

</details>


<details><summary>after, 37 lines of code (will be a lot cleaner):</summary>

```js
class ExampleAfterAPIChanges {
	tween = new TWEEN.Tween({menuPosition: 0})
        .onComplete(() => this.openTween.stop())
		.onUpdate(obj => (someObject.position.x = obj.menuPosition))
		.easing(TWEEN.Easing.Exponential.Out)

	menuOpen = false
	tweenRAF = null

	openMenu = () => {
		this.menuOpen = true

		if (this.tween.isPlaying()) this.tween.stop()

		this.tween.to({menuPosition: -MENU_WIDTH}, 800).start()
		this.tweenLoop()
	}

	closeMenu = () => {
		this.menuOpen = false

		if (this.tween.isPlaying()) this.tween.stop()

		this.tween.to({menuPosition: -MENU_WIDTH}, 800).start()
		this.tweenLoop()
	}

	toggleMenu = () => (this.menuOpen ? this.closeMenu() : this.openMenu())

	tweenLoop() {
		if (this.tweenRAF) return

		this.tweenRAF = requestAnimationFrame(function loop(t) {
			this.tween.update(t)
            if (this.tween.isPlaying()) this.tweenRAF = requestAnimationFrame(loop)
            else this.tweenRAF = null
		})
    }
}
```

</details>

**Comment by trusktr** [comment] 2020-05-29 18:33
@mikebolt I propose we change the last arg of Tween to an options object, so `new TWEEN.Tween({menuPosition: 0}, {group, rememberLastValues: true})`

**Comment by trusktr** [comment] 2020-05-29 18:34
@pchen66 thoughts?

**Comment by trusktr** [comment] 2020-05-29 18:45
What we could do is for backwards compatibility, allow `new TWEEN.Tween(objectWithInitialValues, group, {rememberLastValues: true})`

Then, once we're ready for a breaking change (to the future!) then we can make that the default behavior, so people just write `new TWEEN.Tween(objectWithInitialValues, {group})` or `new TWEEN.Tween(objectWithInitialValues, {group, rememberLastValues: false})` and additionally add a new `reset()` method to reset back to initial state.

**Comment by trusktr** [comment] 2020-05-29 18:55
I deleted some content and moved it to a new issue, #522.

Regarding this issue's bug, it is probably due to this line,

https://github.com/tweenjs/tween.js/blob/master/src/Tween.js#L68

happening inside of `Group` instead of inside of `Tween`. We should re-factor it so a Tween should know when itself is not playing and change its own state. The `Group` should only help _orchestrate_ the Tween instances without changing their internal state.

**Comment by trusktr** [comment] 2020-05-29 19:02
Tracking this in the new [General Project Board](https://github.com/tweenjs/tween.js/projects)

**Comment by trusktr** [comment] 2020-05-30 08:26
> It'd be great to circle back around to making Yoyo work cleanly.

The fixes to yoyo have been merged. This issue still persists though.

Sidenote, with the new change in https://github.com/tweenjs/tween.js/pull/529 calling `start` does nothing if the tween is already started (it returns early in that case). However, you can do the reset by first calling `stop` and _then_ calling `start` again, like this: https://codepen.io/trusktr/pen/2870d850113cad70f06464e3e0bdb72a

Now let's see what needs to be fixed. I think just the repeat values need to be reset.

**Comment by trusktr** [comment] 2020-05-30 20:17
Pull request in progress: https://github.com/tweenjs/tween.js/pull/533

**Comment by trusktr** [comment] 2020-05-31 01:55
Done! Fixed!

Here's your example working as intended: https://codepen.io/trusktr/pen/2870d850113cad70f06464e3e0bdb72a

**Closed** 2020-05-31 01:55 UTC
Labels: Bug, Confirmed, good first issue
